name: Scheduled Request to API

on:
  schedule:
    - cron: '*/12 * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make GET request
        run: curl https://binance.asbel.dev/capture?origin=github
